/* Host-side table generator.  Writes tables.h: the factored quarter-turn
 * transitions and the two pattern databases as const data, so the target
 * program builds nothing at run time and links them into .rodata.
 *
 *   cc -O2 -std=c99 gen_tables.c -o gen_tables && ./gen_tables > tables.h
 */
#include "model.h"

static uint16_t permutation[3][PERMUTATIONS];
static uint16_t orientation[3][ORIENTATIONS];
static uint8_t permutation_distance[PERMUTATIONS];
static uint8_t orientation_distance[ORIENTATIONS];

static void build_transition_tables(void)
{
    for (uint16_t rank = 0; rank < PERMUTATIONS; ++rank) {
        state_t state = {{0}, {0}};
        unrank_state((uint32_t) rank * ORIENTATIONS, &state);
        for (uint8_t face = 0; face < 3; ++face) {
            state_t next = quarter_turn(state, face);
            permutation[face][rank] =
                (uint16_t) (rank_state(&next) / ORIENTATIONS);
        }
    }
    for (uint16_t rank = 0; rank < ORIENTATIONS; ++rank) {
        state_t state = {{0}, {0}};
        unrank_state(rank, &state);
        for (uint8_t face = 0; face < 3; ++face) {
            state_t next = quarter_turn(state, face);
            orientation[face][rank] =
                (uint16_t) (rank_state(&next) % ORIENTATIONS);
        }
    }
}

/* BFS over one factor.  R2 and R' are chained quarter turns; all three cost
 * one move (half-turn metric).  `tab` points at the 3 faces' tables laid out
 * `stride` entries apart. */
static void build_pdb(uint8_t *dist, const uint16_t *tab, uint16_t n,
                      uint16_t stride)
{
    uint16_t *queue = malloc(n * sizeof *queue);
    uint16_t head = 0, tail = 0;
    memset(dist, 0xff, n);
    dist[0] = 0;
    queue[tail++] = 0;
    while (head < tail) {
        uint16_t x = queue[head++];
        for (uint8_t face = 0; face < 3; ++face) {
            uint16_t y = x;
            for (uint8_t turns = 0; turns < 3; ++turns) {
                y = tab[face * stride + y];
                if (dist[y] == 0xff) {
                    dist[y] = (uint8_t) (dist[x] + 1);
                    queue[tail++] = y;
                }
            }
        }
    }
    free(queue);
}

static void dump16(const char *name, const uint16_t *v, int rows, int cols)
{
    printf("static const uint16_t %s[%d][%d] = {\n", name, rows, cols);
    for (int r = 0; r < rows; ++r) {
        printf("    {");
        for (int c = 0; c < cols; ++c)
            printf("%s%u", c % 16 ? "," : (c ? ",\n     " : ""), v[r * cols + c]);
        printf("},\n");
    }
    puts("};");
}

static void dump8(const char *name, const uint8_t *v, int n)
{
    printf("static const uint8_t %s[%d] = {\n    ", name, n);
    for (int i = 0; i < n; ++i)
        printf("%s%u", i % 32 ? "," : (i ? ",\n    " : ""), v[i]);
    puts("\n};");
}

int main(void)
{
    build_transition_tables();
    build_pdb(permutation_distance, &permutation[0][0], PERMUTATIONS,
              PERMUTATIONS);
    build_pdb(orientation_distance, &orientation[0][0], ORIENTATIONS,
              ORIENTATIONS);
    puts("/* Generated by gen_tables.c -- do not edit. */");
    puts("#ifndef TABLES_H\n#define TABLES_H\n#include <stdint.h>\n");
    dump16("permutation", &permutation[0][0], 3, PERMUTATIONS);
    dump16("orientation", &orientation[0][0], 3, ORIENTATIONS);
    dump8("permutation_distance", permutation_distance, PERMUTATIONS);
    dump8("orientation_distance", orientation_distance, ORIENTATIONS);
    puts("\n#endif");
    return 0;
}